# Generated by Django 4.0.3 on 2022-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_payment_admin_note_payment_admin_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
