# Generated by Django 4.0.3 on 2022-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.IntegerField(default=1),
        ),
    ]
