# Generated by Django 4.0.3 on 2022-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
