# Generated by Django 4.0.3 on 2022-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_no_days_alter_booking_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
